title:
  en: MIRCA
  fr: MIRCA
  ru: МИРКА
tagline:
  en: Morgan Initiative for Russian Cultural Affairs
  fr: Morgan Initiative for Russian Cultural Affairs
  ru: Инициатива Морган по Русским Культурным Делам
index:
  en: index.html
  fr: accueil.html
  ru: privet.html
email: russianculturalexchange@gmail.com
description:
  en: Startup initiative that promotes Russian culture in Montreal. It works with local businesses from the Russian-speaking world to create a place where Russian speakers and enthusiasts can mingle, network and share information about the Russian world, its culture and history.
  fr: Oh lah lah
  ru:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mirca.ca"
twitter_username: mircamtl
github_username:  mircamtl
permalink: :title

markdown: kramdown

kramdown:
  parse_block_html: true

defaults:
    - {scope: {path: ""}, values: {layout: "post"}}

prose:
  rooturl: ''
  siteurl: 'http://mirca.ca'
  media: 'img'
  ignore: ['CNAME', '_config.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html']
  metadata:
    _posts:
      - name: "lang"
        field:
          element: "text"
          label: "Language"
          help: "en, fr or ru"
          value: "en"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "The image will be used as a background cover for the post. Can be absolute or relative URL."
          placeholder: "img/cover.jpg"
          type: "url"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Enable comments"
          help: "This will enable comments for the post"
          value: false
      - name: "when"
        field:
          element: "text"
          label: "When"
          help: "The date of the event"
          placeholder: "YYYY-MM-DD HH:MM"
          type: "datetime"
          value: ""
      - name: "where"
        field:
          element: "text"
          label: "Where"
          help: "The place of the event"
          placeholder: "Anticafé Montréal, 294, rue Sainte-Catherine Ouest, H2X 2A1, Montréal QC"
          type: "text"
          value: ""

t:
  en:
    home: "Home"
    about: "About"
    events: "Events"
    programs: "Programs"
  fr:
    home: "Accueil"
    about: "À propos"
    events: "Affiche"
    programs: "Programmes"
  zh:
    home: "首页"
    about: "关于"
  ru:
    home: "Главная"
    about: "О нас"
    events: "События"
    programs: "Программы"
